exp_name: SaltNet
base_on: base.yaml
arch:
  type: TGS_UNet
  args:
    encoder_name: resnext50_32x4d
    classes: 1
    encoder_weights: imagenet
    decoder_attention_type: scse
    aux_params:
      pooling: avg
      dropout: 0.5
      activation: sigmoid
      classes: 1
dataloader:
  type: TgsDataLoader
  args:
    batch_size: 16
    training: True
    num_workers: 8
loss:
  type: Tgs_Loss_v2
metrics:
  - tgs_accuracy
  - tgs_kaggle_iou_mask
trainer:
  type: BasicTrainer
  args:
    epochs: 500
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 11
    tensorboard: False
    save_params_hist: False

#--------valid---------
valid_dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/valid.csv
    batch_size: 64
    training: False
    num_workers: 8
    # TTA: FLIP_UD
valid_metrics:
  [tgs_accuracy, tgs_kaggle_iou, tgs_accurary_classify, tgs_kaggle_iou_mask]
valid_hook:
  - save_seg_result

#--------predict---------
predictor_output: mask
predict_dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/test.csv
    batch_size: 16
    training: False
    num_workers: 4
    # TTA: FLIP_UD
