exp_name: SaltNet_V11_fold0
base_on: tgs.yaml
dataloader:
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/train.csv.fold0
    valid_csv: /root/dataset/tgs-salt-identification-challenge/valid.csv.fold0
