exp_name: tgs-net-aux-depth
version: 2.0
workspace: /root/trash/log
n_gpu: 1
arch:
  type: UNet
  args:
    backbone: resnet34
    num_classes: 1
    pretrained: True
    aux: classify
    aux_num_classes: 1
dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/train_v2.csv
    valid_csv: /root/dataset/tgs-salt-identification-challenge/valid_v2.csv
    batch_size: 8
    training: True
    num_workers: 8
    test_mode: False
    resize: [128, 128]
optimizer:
  type: Adam
  args:
    lr: 1e-5
    weight_decay: 0
loss:
  type: Tgs_Loss
metrics:
  - tgs_accuracy
lr_scheduler:
  type: ReduceLROnPlateau
  args:
    patience: 3
    verbose: True
trainer:
  type: BasicTrainer
  args:
    epochs: 200
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 10
    tensorboard: False
    save_params_hist: False

#--------valid---------
valid_dataloader:
  type: CSVImgDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/valid_v2.csv
    batch_size: 64
    training: False
    num_workers: 8
    test_mode: False
    resize: [128, 128]
valid_metrics:
  [tgs_accuracy, tgs_kaggle_iou, tgs_accurary_classify, tgs_kaggle_iou_v2]
valid_hook:
  - func: plot_seg
    args:
      shuffle: True
      n_samples: 10
  - save_tensor

#--------predict---------
predict_dataloader:
  type: CSVImgDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/test.csv
    batch_size: 8
    training: False
    num_workers: 4
    test_mode: False
    resize: [224, 224]
