exp_name: SaltNet-v8.2
version: 2.0
workspace: /root/trash/log
apex: True
n_gpu: 2
arch:
  type: TGS_UNet
  args:
    encoder_name: resnext50_32x4d
    classes: 1
    encoder_weights: imagenet
    decoder_attention_type: scse
    # activation: sigmoid
    activation: identity
    aux_params:
      pooling: avg
      dropout: 0.5
      activation: sigmoid
      classes: 1
dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/train.csv
    valid_csv: /root/dataset/tgs-salt-identification-challenge/valid.csv
    batch_size: 64
    training: True
    num_workers: 8
optimizer:
  type: SGD
  args:
    lr: 1e-5
    momentum: 0.9
    weight_decay: 0.00001
loss:
  type: Tgs_Loss_v2
metrics:
  - tgs_accuracy
  - tgs_kaggle_iou_mask
lr_scheduler:
  type: CyclicLR
  args:
    base_lr: 0.0000001
    max_lr: 0.0001
    step_size_up: 30
trainer:
  type: BasicTrainer
  args:
    epochs: 500
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 20
    tensorboard: False
    save_params_hist: False

#--------valid---------
valid_dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/valid.csv
    batch_size: 64
    training: False
    num_workers: 8
valid_metrics:
  [tgs_accuracy, tgs_kaggle_iou, tgs_accurary_classify, tgs_kaggle_iou_mask]
valid_hook:
  - save_seg_result

#--------predict---------
predict_dataloader:
  type: TgsDataLoader
  args:
    train_csv: /root/dataset/tgs-salt-identification-challenge/test.csv
    batch_size: 128
    training: False
    num_workers: 4
