exp_name: Camelyon16_vgg16_fcn
version: 2.0
workspace: /root/trash/log
n_gpu: 1
arch:
  type: vgg16_bn_fcn
  args: 
    num_classes: 2
    pretrained: true
dataloader:
  type: ImageFolderLoader
  args:
    train_data_dir: /root/dataset/workspace/CAMELYON16_v2/train
    valid_data_dir: /root/dataset/workspace/CAMELYON16_v2/valid
    batch_size: 64
    shuffle: True
    num_workers: 4
    test_mode: false # this mode will use 16 data for validate the model
    imgs_mean: [0.6600297, 0.4745953, 0.6561866]
    imgs_std: [0.22620466, 0.2393456, 0.18473646]
    size: [224, 224]
optimizer:
  type: Adam
  args:
    lr: 0.0001
    weight_decay: 0
    amsgrad: true
loss: logloss
metrics:
  - accuracy
lr_scheduler:
  type: StepLR
  args:
    step_size: 10
    gamma: 0.5
trainer:
  type: BasicTrainer
  args:
    epochs: 50
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 3
    tensorboard: true
    save_params_hist: false
    n_gpu: 1

# prediction
predict_dataloader:
  type: ImageFolderLoader
  args:
    train_data_dir: /root/dataset/workspace/CAMELYON16_wsi/tumor_001/512
    valid_data_dir: /root/dataset/workspace/CAMELYON16_wsi/tumor_001/512
    batch_size: 1
    shuffle: false
    num_workers: 8
    test_mode: false # this mode will use 16 data for validate the model
    imgs_mean: [0.6600297, 0.4745953, 0.6561866]
    imgs_std: [0.22620466, 0.2393456, 0.18473646]
    size: [1152, 1152]
predict_hook:
  # - func: plot_result
  #   args:
  #     save_path: /root/trash/log/predict.png
  #     nrows: 2
  #     ncols: 2
  #     shuffle: false
  # - func: save_csv
  #   args:
  #     save_path: /root/trash/log/submission.csv

