name: CIFAIR_ResNet
workspace: /tmp/models
n_gpu: 1
model:
  type: ResNetModel
  args: {}
data_loader:
  type: CIFAR10DataLoader
  args:
    data_dir: /tmp/data
    batch_size: 128
    shuffle: true
    validation_split: 0.1
    num_workers: 2
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
loss: cross_entropy
metrics:
  - accuracy
  - top_k_acc
lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1
trainer:
  type: BasicTrainer
  args:
    epochs: 100
    save_dir: /tmp/models/models
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 10
    tensorboard: true
