exp_name: Kaggle_Dog_vs_Cat
version: 2.0
workspace: /root/trash/log
n_gpu: 1
arch:
  type: resnet18
  args: 
    num_classes: 10
dataloader:
  type: ImageFolderLoader
  args:
      train_data_dir: /root/dataset/workspace/CAMELYON16_v2/train
      batch_size: 128
      shuffle: True
      num_workers: 4
      test_mode: false # this mode will use 16 data for validate the model
      imgs_mean: [0.485, 0.456, 0.406]
      imgs_std: [0.229, 0.224, 0.225]
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
loss: logloss
metrics:
  - accuracy
lr_scheduler:
  type: StepLR
  args:
    step_size: 2
    gamma: 0.5
trainer:
  type: BasicTrainer
  args:
    epochs: 50
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 3
    tensorboard: true
    save_params_hist: false
    n_gpu: 1

# prediction
predict_dataloader:
  type: ImageFolderLoader
  args:
    train_data_dir: /root/dataset/workspace/CAMELYON16_v2/train
    batch_size: 64
    shuffle: True
    num_workers: 4
    test_mode: false # this mode will use 16 data for validate the model
    imgs_mean: [0.485, 0.456, 0.406]
    imgs_std: [0.229, 0.224, 0.225]
predict_hook:
  - func: plot_result
    args:
      save_path: /root/trash/log/predict.png
      nrows: 10
      ncols: 10
      shuffle: false
  - func: save_csv
    args:
      save_path: /root/trash/log/submission.csv

