exp_name: Kaggle_Dog_vs_Cat_v3_vanilla
version: 2.0
workspace: /root/trash/log
n_gpu: 2
arch:
  type: VanillaModel
  args:
    num_classes: 2
    pretrained: True
dataloader:
  type: CSVDataLoader
  args:
    train_csv: /root/dataset/dogs-vs-cats-redux-kernels-edition/train.csv
    valid_csv: /root/dataset/dogs-vs-cats-redux-kernels-edition/valid.csv
    batch_size: 32
    training: True
    num_workers: 16
    test_mode: False
    resize: [320, 320]
    data_augement: True
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0.003
    amsgrad: True
loss: logloss
metrics:
  - accuracy
  - logloss
lr_scheduler:
  type: StepLR
  args:
    step_size: 5
    gamma: 0.5
trainer:
  type: BasicTrainer
  args:
    epochs: 100
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 5
    tensorboard: True
    save_params_hist: False
    n_gpu: 2

valid_dataloader:
  type: CSVDataLoader
  args:
    train_csv: /root/dataset/dogs-vs-cats-redux-kernels-edition/valid.csv
    batch_size: 64
    training: False
    num_workers: 4
    test_mode: False
    resize: [320, 320]

# prediction
predict_dataloader:
  type: CSVDataLoader
  args:
    train_csv: /root/dataset/dogs-vs-cats-redux-kernels-edition/test.csv
    batch_size: 64
    training: False
    num_workers: 4
    test_mode: False
    resize: [320, 320]
predict_hook:
  - func: plot_result
    args:
      save_path: predict.png
      nrows: 5
      ncols: 5
      shuffle: False
      label_map:
        0: cat
        1: dog
  - func: save_csv
    args:
      dim: 1
      save_path: submission.csv
